import { config } from "dotenv";
import path from "node:path";
import { z } from "zod";

const envFile = process.env.NODE_ENV === "test" ? ".env.test" : ".env";

config({ path: path.resolve(process.cwd(), envFile) });
config({ path: path.resolve(process.cwd(), "../../", envFile), override: false });

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().default(4000),
  DATABASE_URL: z.string().min(1),
  OPENCLAW_WS_URL: z.string().default("wss://47.250.122.37/"),
  OPENCLAW_BASIC_USER: z.string().optional(),
  OPENCLAW_BASIC_PASS: z.string().optional(),
  OPENCLAW_GATEWAY_TOKEN: z.string().optional(),
  OPENCLAW_REQUEST_SCOPES: z.string().default("operator.read,operator.write"),
  OPENCLAW_CLIENT_ID: z.string().default("openclaw-control-ui"),
  OPENCLAW_CLIENT_MODE: z.string().default("webchat"),
  OPENCLAW_CLIENT_PLATFORM: z.string().default("MacIntel"),
  OPENCLAW_CLIENT_VERSION: z.string().default("vdev"),
  OPENCLAW_CLIENT_INSTANCE_ID: z.string().default("ticket-core"),
  OPENCLAW_CLIENT_ORIGIN: z.string().default("https://47.250.122.37"),
  OPENCLAW_AGENT_ID: z.string().default("main"),
  OPENCLAW_AGENT_SESSION_KEY: z.string().default("agent:main:main"),
  OPENCLAW_AGENT_ID_RETRIEVAL: z.string().default("retrieval"),
  OPENCLAW_AGENT_ID_CLARIFY: z.string().default("clarify"),
  OPENCLAW_AGENT_ID_EXECUTION: z.string().default("execution"),
  OPENCLAW_AGENT_SESSION_PREFIX: z.string().default("nf"),
  OPENCLAW_AGENT_TIMEOUT_MS: z.coerce.number().default(30000),
  OPENCLAW_ALLOW_SELF_SIGNED: z.coerce.boolean().default(false),
  OPENCLAW_SEARCH_INDEX: z.string().default("public_kb"),
  OPENCLAW_CONNECT_TIMEOUT_MS: z.coerce.number().default(10000),
  OPENCLAW_METHOD_TIMEOUT_MS: z.coerce.number().default(30000),
  OPENCLAW_SEARCH_TIMEOUT_MS: z.coerce.number().default(12000),
  OPENCLAW_MAX_RETRIES: z.coerce.number().default(2),
  OPENCLAW_CIRCUIT_BREAKER_THRESHOLD: z.coerce.number().default(5),
  OPENCLAW_SEARCH_TOP_K: z.coerce.number().default(5),
  OPENCLAW_DEEP_SEARCH_MAX_ROUNDS: z.coerce.number().default(3),
  AI_SEARCH_ANSWER_CONFIDENCE_THRESHOLD: z.coerce.number().default(0.62),
  AGENT_RESOLUTION_CONFIDENCE_THRESHOLD: z.coerce.number().default(0.76),
  DISABLE_AI_TRIAGE_FALLBACK: z.coerce.boolean().default(true),
  FEATURE_KB_GROUNDED_SEARCH: z.coerce.boolean().default(true),
  FEATURE_QUICK_TICKET: z.coerce.boolean().default(true),
  FEATURE_DEEP_RETRIEVAL: z.coerce.boolean().default(true),
  FEATURE_AI_MULTI_TURN_HANDOFF: z.coerce.boolean().default(true),
  AI_SEARCH_MAX_CLARIFICATION_ROUNDS: z.coerce.number().int().min(1).max(10).default(3),
  ONES_SYNC_ENCRYPTION_KEY: z.string().default("dev-only-change-me-32-char-key"),
  ONES_SYNC_DEFAULT_BASE_URL: z.string().default("https://ones.com"),
  ONES_SYNC_DEFAULT_PROJECTS_PATH: z.string().default("/project/projects"),
  ONES_SYNC_DEFAULT_TICKET_TYPES_PATH: z.string().default("/project/issueTypes"),
  ONES_SYNC_DEFAULT_FIELDS_PATH_TEMPLATE: z.string().default("/project/issueFields"),
  ONES_SYNC_DEFAULT_CREATE_TICKET_PATH: z.string().default("/project/issues"),
  GITHUB_KB_ENABLED: z.coerce.boolean().default(false),
  GITHUB_API_BASE_URL: z.string().default("https://api.github.com"),
  GITHUB_TOKEN_READONLY: z.string().optional(),
  GITHUB_WEBHOOK_SECRET: z.string().optional(),
  GITHUB_KB_ALLOW_BROAD_SCOPES: z.coerce.boolean().default(false),
  GITHUB_KB_BOOTSTRAP_REPO_URL: z.string().optional(),
  GITHUB_KB_BOOTSTRAP_BRANCH: z.string().default("main"),
  GITHUB_KB_BOOTSTRAP_INCLUDE_PATHS: z.string().default("**/*.md"),
  GITHUB_KB_BOOTSTRAP_EXCLUDE_PATHS: z.string().default(""),
  GITHUB_KB_BOOTSTRAP_POLLING_INTERVAL_SECONDS: z.coerce.number().int().min(30).max(86400).default(300),
  GITHUB_KB_CHUNK_TARGET_TOKENS: z.coerce.number().int().min(100).max(3000).default(500),
  GITHUB_KB_CHUNK_OVERLAP_TOKENS: z.coerce.number().int().min(0).max(500).default(60),
  GITHUB_KB_VECTOR_DIM: z.coerce.number().int().min(64).max(4096).default(1536),
  GITHUB_KB_EMBEDDING_PROVIDER: z.enum(["mock", "openai"]).default("mock"),
  GITHUB_KB_EMBEDDING_API_BASE: z.string().default("https://api.openai.com/v1"),
  GITHUB_KB_EMBEDDING_API_KEY: z.string().optional(),
  GITHUB_KB_EMBEDDING_MODEL: z.string().default("text-embedding-3-small"),
  GITHUB_KB_EMBEDDING_MAX_RETRIES: z.coerce.number().int().min(0).max(5).default(2),
  GITHUB_KB_PROFILE_SEARCH_TOPK: z.coerce.number().int().min(1).max(30).default(5),
  GITHUB_KB_PROFILE_AGENT_TOPK: z.coerce.number().int().min(1).max(30).default(12),
  GITHUB_KB_PROFILE_SEARCH_CONFIDENCE_THRESHOLD: z.coerce.number().min(0).max(1).default(0.6),
  GITHUB_KB_PROFILE_AGENT_CONFIDENCE_THRESHOLD: z.coerce.number().min(0).max(1).default(0.45),
  GITHUB_KB_POLL_BATCH_SIZE: z.coerce.number().int().min(1).max(200).default(5),
  GITHUB_KB_WORKER_BATCH_SIZE: z.coerce.number().int().min(1).max(200).default(2),
  GITHUB_KB_WORKER_INTERVAL_SECONDS: z.coerce.number().int().min(5).max(3600).default(30)
});

export const env = envSchema.parse(process.env);
