INSERT INTO tickets (
  id, ticket_no, title, description, service_category, priority, status,
  customer_id, customer_name, customer_email, assignee_type, assignee_name,
  ai_run_seq, sla_due_at, first_response_due_at, resolution_due_at,
  ones_ticket_type_key, ones_sync_status, ai_mode_snapshot, ai_last_trace_id,
  ai_last_action, ai_last_confidence, ai_last_model, ai_last_fallback_applied,
  assigned_at, last_customer_reply_at, last_agent_reply_at, ai_suggestion_pending,
  created_at, updated_at
) VALUES
(
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010001',
  'T-90010001',
  'Cannot login after SSO migration',
  'Users in US region receive 401 after successful SSO redirect.',
  'technical_support',
  'P1',
  'IN_PROGRESS',
  'cust_acme_001',
  'Acme Corp',
  'itops@acme.com',
  'SUPPORT_TEAM',
  'Support Team',
  2,
  NOW() + INTERVAL '35 minutes',
  NOW() - INTERVAL '20 minutes',
  NOW() + INTERVAL '35 minutes',
  'incident',
  'synced',
  'AI_ON',
  'trace_login_001',
  'ask_user',
  0.78,
  'glm-5',
  FALSE,
  NOW() - INTERVAL '45 minutes',
  NOW() - INTERVAL '10 minutes',
  NOW() - INTERVAL '30 minutes',
  TRUE,
  NOW() - INTERVAL '2 hours',
  NOW() - INTERVAL '5 minutes'
),
(
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010002',
  'T-90010002',
  'Webhook delivery delays over 5 minutes',
  'Production webhook retries are delayed and causing order state mismatch.',
  'technical_support',
  'P2',
  'IN_PROGRESS',
  'cust_nova_002',
  'Nova Retail',
  'ops@nova.io',
  'SUPPORT_TEAM',
  'Support Team',
  1,
  NOW() + INTERVAL '2 hours 20 minutes',
  NOW() - INTERVAL '15 minutes',
  NOW() + INTERVAL '2 hours 20 minutes',
  'incident',
  'synced',
  'AI_ON',
  'trace_webhook_002',
  'resolve',
  0.92,
  'glm-5',
  FALSE,
  NOW() - INTERVAL '50 minutes',
  NOW() - INTERVAL '25 minutes',
  NOW() - INTERVAL '40 minutes',
  TRUE,
  NOW() - INTERVAL '3 hours',
  NOW() - INTERVAL '8 minutes'
),
(
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010003',
  'T-90010003',
  'Need export API rate-limit increase',
  'Customer requests temporary API burst for quarter-end reconciliation.',
  'feature_consulting',
  'P3',
  'ESCALATED_RND',
  'cust_orbit_003',
  'Orbit Finance',
  'platform@orbitfin.com',
  'RND_TEAM',
  'R&D Team',
  1,
  NOW() + INTERVAL '6 hours',
  NOW() - INTERVAL '1 hour',
  NOW() + INTERVAL '6 hours',
  'service_request',
  'synced',
  'AI_ON',
  'trace_rate_003',
  'escalate',
  0.88,
  'glm-5',
  FALSE,
  NOW() - INTERVAL '4 hours',
  NOW() - INTERVAL '2 hours',
  NOW() - INTERVAL '3 hours',
  FALSE,
  NOW() - INTERVAL '6 hours',
  NOW() - INTERVAL '12 minutes'
),
(
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010004',
  'T-90010004',
  'Billing invoice tax field mismatch',
  'EU invoices display zero VAT after account ownership transfer.',
  'account_issue',
  'P2',
  'WAITING_CUSTOMER',
  'cust_halo_004',
  'Halo Studio',
  'finance@halo.studio',
  'SUPPORT_TEAM',
  'Support Team',
  1,
  NOW() + INTERVAL '9 hours',
  NOW() - INTERVAL '3 hours',
  NOW() + INTERVAL '9 hours',
  'incident',
  'synced',
  'AI_OFF',
  'trace_billing_004',
  'ask_user',
  0.81,
  'glm-5',
  FALSE,
  NOW() - INTERVAL '5 hours',
  NOW() - INTERVAL '30 minutes',
  NOW() - INTERVAL '2 hours',
  TRUE,
  NOW() - INTERVAL '10 hours',
  NOW() - INTERVAL '6 minutes'
),
(
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010005',
  'T-90010005',
  'Intermittent timeout on data import',
  'Import jobs fail randomly with timeout after 120s.',
  'technical_support',
  'P1',
  'OPEN',
  'cust_zen_005',
  'Zen Mobility',
  'support@zenmobility.com',
  'SUPPORT_TEAM',
  'Support Team',
  0,
  NOW() + INTERVAL '50 minutes',
  NOW() + INTERVAL '20 minutes',
  NOW() + INTERVAL '50 minutes',
  'incident',
  'synced',
  'AI_ON',
  NULL,
  NULL,
  NULL,
  NULL,
  FALSE,
  NOW() - INTERVAL '10 minutes',
  NOW() - INTERVAL '10 minutes',
  NULL,
  FALSE,
  NOW() - INTERVAL '40 minutes',
  NOW() - INTERVAL '4 minutes'
),
(
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010006',
  'T-90010006',
  'Password reset completed but login still blocked',
  'Customer confirmed reset email received, but account remains locked.',
  'account_issue',
  'P3',
  'RESOLVED',
  'cust_luma_006',
  'Luma Health',
  'admin@luma.health',
  'SUPPORT_TEAM',
  'Support Team',
  1,
  NOW() - INTERVAL '2 hours',
  NOW() - INTERVAL '20 hours',
  NOW() - INTERVAL '2 hours',
  'incident',
  'synced',
  'AI_ON',
  'trace_pwd_006',
  'resolve',
  0.95,
  'glm-5',
  FALSE,
  NOW() - INTERVAL '22 hours',
  NOW() - INTERVAL '21 hours',
  NOW() - INTERVAL '20 hours',
  FALSE,
  NOW() - INTERVAL '24 hours',
  NOW() - INTERVAL '1 hour'
)
ON CONFLICT (ticket_no) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  priority = EXCLUDED.priority,
  status = EXCLUDED.status,
  customer_name = EXCLUDED.customer_name,
  customer_email = EXCLUDED.customer_email,
  assignee_type = EXCLUDED.assignee_type,
  assignee_name = EXCLUDED.assignee_name,
  sla_due_at = EXCLUDED.sla_due_at,
  first_response_due_at = EXCLUDED.first_response_due_at,
  resolution_due_at = EXCLUDED.resolution_due_at,
  ones_ticket_type_key = EXCLUDED.ones_ticket_type_key,
  ones_sync_status = EXCLUDED.ones_sync_status,
  ai_mode_snapshot = EXCLUDED.ai_mode_snapshot,
  ai_last_trace_id = EXCLUDED.ai_last_trace_id,
  ai_last_action = EXCLUDED.ai_last_action,
  ai_last_confidence = EXCLUDED.ai_last_confidence,
  ai_last_model = EXCLUDED.ai_last_model,
  ai_last_fallback_applied = EXCLUDED.ai_last_fallback_applied,
  assigned_at = EXCLUDED.assigned_at,
  last_customer_reply_at = EXCLUDED.last_customer_reply_at,
  last_agent_reply_at = EXCLUDED.last_agent_reply_at,
  ai_suggestion_pending = EXCLUDED.ai_suggestion_pending,
  updated_at = NOW();

INSERT INTO ai_runs (
  id, ticket_id, idempotency_key, input_json, response_json, status,
  trace_id, decision_action, model_name, confidence, evidence_json, fallback_applied, prompt_hash, created_at
) VALUES
(
  '5cf7f261-57e2-49f2-860e-4d7e20020001',
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010001',
  'seed-run-90010001',
  '{"source":"seed"}'::jsonb,
  '{"action":"ask_user","confidence":0.78,"reasoning_summary":"Likely SSO scope mismatch after migration; ask customer for failed request ID and affected user sample.","evidence":["Auth runbook - SSO scope checklist","Recent tenant migration event"]}'::jsonb,
  'completed',
  'trace_login_001',
  'ask_user',
  'glm-5',
  0.78,
  '["Auth runbook - SSO scope checklist","Recent tenant migration event"]'::jsonb,
  FALSE,
  'seed_hash_001',
  NOW() - INTERVAL '20 minutes'
),
(
  '5cf7f261-57e2-49f2-860e-4d7e20020002',
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010002',
  'seed-run-90010002',
  '{"source":"seed"}'::jsonb,
  '{"action":"resolve","confidence":0.92,"reasoning_summary":"Matched known webhook retry backlog pattern; restart worker pool and replay dead-letter queue.","evidence":["Webhook runbook section 4.2","Incident RCA #2026-02-17"]}'::jsonb,
  'completed',
  'trace_webhook_002',
  'resolve',
  'glm-5',
  0.92,
  '["Webhook runbook section 4.2","Incident RCA #2026-02-17"]'::jsonb,
  FALSE,
  'seed_hash_002',
  NOW() - INTERVAL '35 minutes'
)
ON CONFLICT (idempotency_key) DO NOTHING;

INSERT INTO ticket_messages (
  id, ticket_id, author_type, author_name, body, attachments, is_ai_generated, ai_confidence, created_at
) VALUES
(
  'f5ed7f18-882c-4d8e-9a1c-9dbf30030001',
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010001',
  'CUSTOMER',
  'Acme Corp',
  'Users report login loop and 401 after SSO callback since this morning.',
  '[]'::jsonb,
  FALSE,
  NULL,
  NOW() - INTERVAL '2 hours'
),
(
  'f5ed7f18-882c-4d8e-9a1c-9dbf30030002',
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010001',
  'AGENT',
  'AI Assistant',
  'Please share one failed request ID, user email sample, and callback URL for quick verification.',
  '[]'::jsonb,
  TRUE,
  0.78,
  NOW() - INTERVAL '18 minutes'
),
(
  'f5ed7f18-882c-4d8e-9a1c-9dbf30030003',
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010002',
  'CUSTOMER',
  'Nova Retail',
  'Order webhook delay jumped from 5s to 6m in production.',
  '[]'::jsonb,
  FALSE,
  NULL,
  NOW() - INTERVAL '3 hours'
),
(
  'f5ed7f18-882c-4d8e-9a1c-9dbf30030004',
  'a5f4c9a1-7032-4fd2-b1b2-7b5f70010002',
  'AGENT',
  'AI Assistant',
  'Applied queue rebalance suggestion. Please confirm webhook latency in the next 10 minutes.',
  '[]'::jsonb,
  TRUE,
  0.92,
  NOW() - INTERVAL '30 minutes'
)
ON CONFLICT (id) DO NOTHING;
